### ISSUE TITLE
I need to change the resolution and the channels size for fine-tuning

### ISSUE THREAD

**Issue by almahdir1** [shkarupa-alex/tfswin#1]
I tried to use different input size such as 256 x 256 x 11 and use the pretrained weights. It did not work. Any help on this.

**Comment by shkarupa-alex** [comment]
Published model works in the same way as any standard keras.applications.*, e.g. as keras.applications.resnet.ResNet50.
So, you can't use pretrained weighs when input channels != 3.

Usually you can do such trick:
```python
from keras import layers

input_image = layers.Input(name='image', shape=(None, None, 3), dtype='float32')
base_model = SwinTransformerTiny224(input_tensor=input_image, include_top=False, weights='imagenet')

ext_config = base_model.get_config()
ext_config['layers'][0]['batch_input_shape'] = base_config['layers'][0]['batch_input_shape'][:-1] + (11,)

ext_model = Model.from_config(ext_config)

# first conv layer kernel will have different shape when channels=3 (pretrained weights) and when channels=11 (your case)
# so you need to take original conv weights and pad them with zeros to requred shape
# here is an example for another model, you need to find right shape and fix this exaple
ext_weights = [
    w if w.shape != (7, 7, 3, 64)
    else np.concatenate([w, np.zeros((7, 7, 8, 64))], axis=2) 
    for w in base_model.get_weights()
]
ext_model.set_weights(ext_weights)

# now ext_model will have required channel size and most of the weights will be pretrained
# if you want to use this new model as some feature extractor you must freeze it (set trainable=False) except the first conv layer
```

**Comment by almahdir1** [comment]
Thank you very much for the response.

What you mean by "base_config" ?
ext_config['layers'][0]['batch_input_shape'] = base_config['layers'][0]['batch_input_shape'][:-1] + (11,)
if I want to retrain I think I should add a dense layer. 
Here is my edit:

from keras import layers, models
input_image = layers.Input(name='image', shape=(256, 256, 3), dtype='float32')
base_model = SwinTransformerTiny224(include_top=False, weights='imagenet')(input_image)
base_model = layers.Dense(2, activation='softmax')(base_model)
model = models.Model(inputs=input_image, outputs=base_model)
ext_config = model.get_config()
#ext_config['layers'][0]['batch_input_shape'] = base_config['layers'][0]['batch_input_shape'][:-1] + (11,)
ext_config['layers'][0]['batch_input_shape'] = (None, 256, 256, 11)

ext_model = tf.keras.Model.from_config(ext_config)

ext_weights = [
    w if w.shape != (7, 7, 3, 64)
    else np.concatenate([w, np.zeros((7, 7, 8, 64))], axis=2) 
    for w in model.get_weights()
]
ext_model.set_weights(ext_weights)

but I still have an error message as follows

ValueError: Shapes (None, 2) and (None, 8, 8, 2) are incompatible

**Comment by shkarupa-alex** [comment]
>>What you mean by "base_config" ?
Misspelling, should be ext_config

>>if I want to retrain I think I should add a dense layer.
If you want to use model for classification you may pass include_top=False in model constructor.
After constructing extended model you should add Global Avg/Max pooling and Dense layers at the top.
In any case due to change of input channels you should retrain (not freeze) first conv layer (patch embedding).

>>ValueError: Shapes (None, 2) and (None, 8, 8, 2) are incompatible
When include_top=False you should use Global pooling before Dense

**Comment by almahdir1** [comment]
Awesome. That is what i have done. Thank you very much for the help.
